export const STRIPE_SIGN_IN_SUCCESS = "STRIPE_SIGN_IN_SUCCESS";
export const STRIPE_SIGN_IN_FAIL = "STRIPE_SIGN_IN_FAIL";
export const STRIPE_SIGN_IN_VALIDATION = "STRIPE_SIGN_IN_VALIDATION";
export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_OUT = "SIGN_OUT";
